<template>
    <div class="col-md-9 ml-sm-auto col-lg-10 px-4" style="margin-top: -520px">
        <div class="d-flex justify-content-center" >
            <div class="jumbotron">
                <h1 class="display-4">KİŞİSEL VERİLERİN KORUNMASI!</h1>
                <p class="lead">Test test test

                    .</p>
                <hr class="my-4">
                <ol>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a orci at ex vestibulum blandit. Pellentesque eget libero volutpat, sagittis quam id, porttitor massa. Suspendisse ac cursus dolor. Curabitur massa dui, auctor ac sem non, eleifend lobortis ligula. Praesent finibus lorem a risus hendrerit, non vehicula orci dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin blandit tempus elit, ut ullamcorper orci gravida ullamcorper. Mauris dapibus quis tellus in dictum. Praesent pharetra felis ut sem interdum, ut dignissim elit feugiat. Nam ac nisl a enim maximus consequat quis ac purus. Fusce odio sem, fringilla at purus et, mattis lacinia augue. Interdum et malesuada fames ac ante ipsum primis in faucibus.</li>
                </ol>
            </div>
        </div>
    </div>
</template>

<script>

</script>

<style scoped>

</style>
